  example-christmas1:
    title:
      text:
      # "Merry Christmas" will be translated to the clients language
      # in Dutch for example it will say "vrolijk kerstfeest"
      # NOTE: You can't use colors inside the translate tags
      - '&f✰ &b&l<translate from="en" to="{locale_short}">Merry Christmas</translate> &f✰'
      interval: 2
      ramdom: false
    header:
      text:
      # The header is long (colors included) because
      # it is not animated and can be used as a static
      # long line
      - '&1&m--&9&m--&b&m---&f&m----&b&m---&9&m--&1&m--'
      interval: -1
      random: false
    label-1:
      text:
      - '&f❄ &8&l> &9&lPlayer:'
      - '&b❄ &8&l> &9&lPlayer:'
      - '&9❄ &8&l> &9&lPlayer:'
      - '&1❄ &8&l> &9&lPlayer:'
      - '&9❄ &8&l> &9&lPlayer:'
      - '&b❄ &8&l> &9&lPlayer:'
      interval: 4
      random: false
    info-1:
      text:
      - ' &o{player}'
      interval: 10
      random: false
    label-2:
      text:
      - '&b❄ &8&l> &9&lHealth:'
      - '&9❄ &8&l> &9&lHealth:'
      - '&1❄ &8&l> &9&lHealth:'
      - '&9❄ &8&l> &9&lHealth:'
      - '&b❄ &8&l> &9&lHealth:'
      - '&f❄ &8&l> &9&lHealth:'
      interval: 4
      random: false
    info-2:
      text:
      - ' {healthbar}'
      interval: 1
      random: false
    footer:
      text:
      - '&1&m--&9&m--&b&m---&f&m----&b&m---&9&m--&1&m--'
      interval: -1
      random: false