  example-christmas2:
    title:
      text:
      # "Merry Christmas" will be translated to the clients language
      # in Dutch for example it will say "vrolijk kerstfeest"
      # NOTE: You can't use colors inside the translate tags
      - '<glow repeatfirstframe="10" startglowcolor="&b&l" glowcolor="&9&l" endglowcolor="&b&l" normalcolor="&f&l">MaximMC</glow>'
      interval: 3
      ramdom: false
    header:
      text:
      # The header is long (colors included) because
      # it is not animated and can be used as a static
      # long line
      - '&1&m--&9&m--&b&m---&f&m----&b&m---&9&m--&1&m--'
      interval: -1
      random: false
    label-1:
      text:
      - '<delay times="15"><single></single></delay>'
      # The frames above only run on the start of the board
      # but are skipped after running once.
      # Calculation:
      #     line1: 15 * 4ticks = 60ticks
      
      - '&f❄ &8&l> &9&lPlayer:'
      - '&b❄ &8&l> &9&lPlayer:'
      - '&9❄ &8&l> &9&lPlayer:'
      - '&1❄ &8&l> &9&lPlayer:'
      - '&9❄ &8&l> &9&lPlayer:'
      - '&b❄ &8&l> &9&lPlayer:'
      interval: 4
      random: false
    info-1:
      text:
      - '<single></single>'
      - '<single>&bMaximMC</single>'
      - '<single>&bMaximMC &9Wishes</single>'
      - '<single>&bMaximMC &9Wishes &fyou</single>'
      - '<single><delay times="2">&bMaximMC &9Wishes &fyou &ba</delay></single>'
      # The frames above only run on the start of the board
      # but are skipped after running once.
      # Calculation:
      #     10 + 10 + 10 + 10 + (2x10) = 60ticks
      
      - ' &o{player}'
      interval: 10
      random: false
    label-2:
      text:
      - '<delay times="10"><single></single></delay>'
      - '<single><delay times="5">&b&l<translate from="en" to="{locale_short}">Merry Christmas</translate></delay></single>'   
      # The frames above only run on the start of the board
      # but are skipped after running once.
      # Calculation:
      #     line1: 10 * 4ticks = 40ticks
      #     line2: 5  * 4ticks = 20ticks
      #     Total: 60ticks
      
      - '&b❄ &8&l> &9&lHealth:'
      - '&9❄ &8&l> &9&lHealth:'
      - '&1❄ &8&l> &9&lHealth:'
      - '&9❄ &8&l> &9&lHealth:'
      - '&b❄ &8&l> &9&lHealth:'
      - '&f❄ &8&l> &9&lHealth:'
      interval: 4
      random: false
    info-2:
      text:
      - '<delay times="60"><single></single></delay>'
      # The frames above only run on the start of the board
      # but are skipped after running once.
      # Calculation:
      #     60 * 1tick = 60ticks
      
      - ' {healthbar}'
      interval: 1
      random: false
    footer:
      text:
      - '&1&m--&9&m--&b&m---&f&m----&b&m---&9&m--&1&m--'
      interval: -1
      random: false